//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testRAF.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filmler
    {
        public int TID { get; set; }
        public string title { get; set; }
        public Nullable<int> id { get; set; }
        public Nullable<int> izlenme { get; set; }
        public Nullable<int> begenme { get; set; }
        public Nullable<int> dahasonraizle { get; set; }
        public Nullable<int> yorumlar { get; set; }
        public Nullable<int> FResimId { get; set; }
        public string imdb_id { get; set; }
    
        public virtual filmResim filmResim { get; set; }
    }
}
