//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testRAF.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class listeler
    {
        public int ListeId { get; set; }
        public string ListeBaslik { get; set; }
        public string ListeAciklama { get; set; }
        public string ListeIcerik { get; set; }
        public Nullable<System.DateTime> ListeTarih { get; set; }
        public Nullable<int> begenme { get; set; }
        public Nullable<int> goruntulenme { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> LResimId { get; set; }
    
        public virtual User User { get; set; }
        public virtual listeResim listeResim { get; set; }
    }
}
