//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testRAF.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class listerafDBEntities4 : DbContext
    {
        public listerafDBEntities4()
            : base("name=listerafDBEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<begenilenler> begenilenlers { get; set; }
        public virtual DbSet<dahasonraizle> dahasonraizles { get; set; }
        public virtual DbSet<izlenenler> izlenenlers { get; set; }
        public virtual DbSet<Roller> Rollers { get; set; }
        public virtual DbSet<uDetay> uDetays { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Yorumlar> Yorumlars { get; set; }
        public virtual DbSet<resimler> resimlers { get; set; }
        public virtual DbSet<Rutbeler> Rutbelers { get; set; }
        public virtual DbSet<Filmler> Filmlers { get; set; }
        public virtual DbSet<filmResim> filmResims { get; set; }
        public virtual DbSet<listeler> listelers { get; set; }
        public virtual DbSet<listeResim> listeResims { get; set; }
    }
}
